#!/usr/bin/bash

make

inotifywait \
  --event create,delete,modify,attrib \
  --monitor \
  --recursive \
  --exclude build \
  . | \
while read; do
  make
done &

(sleep 1 && ${BROWSER-chromium} 127.0.0.1:8000) &

cd build
python3 -m http.server 8000
