#!/usr/bin/env python3

import sys

import jinja2


def main():
    if len(sys.argv) != 2:
        print('usage: {} template_file'.format(sys.argv[0]), file=sys.stderr)
        sys.exit(1)

    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader('.'),
        trim_blocks=True,
        lstrip_blocks=True,
    )

    template = env.get_template(sys.argv[1])

    print(template.render(
        site_title='Jonah Bernhard',
    ))


if __name__ == "__main__":
    main()
