#!/usr/bin/env python3

import time

import bibtexparser
import jinja2
import yaml


def obfuscate(string):
    """
    Encode a string to html character entities.
    For email address obfuscation.

    """
    return ''.join(['&#{:d};'.format(ord(i)) for i in string])


def main():
    with open('data/papers.bib') as f:
        papers = bibtexparser.load(f).entries

    with open('data/site.yml') as f:
        site_data = yaml.load(f)

    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader('.'),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters.update(
        strftime=time.strftime,
        obfuscate=obfuscate
    )

    template = env.get_template('index.html')

    print(template.render(
        papers=papers,
        **site_data
    ))


if __name__ == "__main__":
    main()
